services:
  nodejslambda:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:8080
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - "./lambda:/var/task"

      #entrypoint: "/aws-lambda/aws-lambda-rie"
      #  - "~/.aws-lambda-rie:/aws-lambda"
      #  # - ./function:/usr/app/function

